### ISSUE TITLE
hpack incompatible with cabal.project

### ISSUE THREAD

**Issue by kquick** [SPY/haskell-wasm#17]
We are currently using `haskell-wasm` as a library in a larger configuration and need to use the source version for updates that have not been released to hackage yet.  [While this is a transient issue, it's also a fairly common occurrence.]

We have a `cabal.project` file we can use to reference our local source version of haskell-wasm, but in order for that to work, we first need to run `hpack` in the haskell-wasm directory to generate a `.cabal` file, which adds a bit of overhead to new checkouts and also CI maintenance.

I would like to  ask if you would be willing to switch from an `hpack`-based configuration to a `.cabal` file (I'm willing to submit the PR for this change) or if you have specific reasons for wanting to stay with `package.yaml` and `hpack`?

**Comment by SPY** [comment]
Hi @kquick 

I started the project when stack was much easier to use than cabal to ramp up a project.
I think times changed, and it is a good idea to switch to a cabal-based solution.
It would be really great if you can help with it, coz I'm out of reach a machine with Haskell setup up to next week.

Best, Ilya

**Comment by kquick** [comment]
Hi Ilya,  

That sounds great, I'll submit a PR shortly.  

My plan is to replace the package.yaml with a haskell-wasm.cabal file, but I wasn't planning on removing the stack.yaml file.  I don't use stack, so I don't know if that still works for stack users, but I didn't want to disable that peremptorily.

**Comment by kquick** [comment]
See https://github.com/SPY/haskell-wasm/pull/18
